services:
  db:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123
      POSTGRES_DB: edir_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d edir_db"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
#  app:
#    build:
#      context: app
#      dockerfile: app/Dockerfile
#    container_name: spring_app
#    ports:
#      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/edir_db
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=Admin123
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
