spring.application.name=app
spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=none

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/edir_db
spring.datasource.username=admin
spring.datasource.password=Admin123
spring.jpa.hibernate.ddl-auto=update