spring.application.name=app

# Disable container overrides during H2 testing
spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=none

# REMOVED: DEFAULT_NULL_TO_ORDER_ONLY=TRUE;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS edir\\;SET SCHEMA edir\\;CREATE SCHEMA IF NOT EXISTS contributions\\;SET SCHEMA contributions
spring.datasource.username=sa
spring.datasource.password=

#####
###
# Ensures Hibernate maps objects correctly to H2's PostgreSQL compatibility mode
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
